server:
  port: 9002
spring:
  application:
    name: file
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
file:
  path: D:/file/imooc/course/
  domain: http://127.0.0.1:9003/file/f/
# oss
accessKeyId: LTAI4Fq5ykqLQnnx7ST1YJx5
accessKeySecret: ZnTghz55kbvomCNyY3KuOefZpjBtTv
endpoint: http://oss-cn-shanghai.aliyuncs.com
ossDomain: http://imooc-course.oss-cn-shanghai.aliyuncs.com/
bucket: imooc-course

