spring:
  datasource:
    url: jdbc:mysql://localhost:3306/course?characterEncoding=UTF8&autoReconnect=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
logging:
  level:
    com:
      course:
        server:
          mapper=trace:
