server:
  port: 9003
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: system  #请求 http://localhost:8100/data-service1/test会转发到data-producer服务
          uri: http://localhost:9100  #在服务注册中心找服务名为 data-producer的服务
          predicates:
            - Path=/system/*  #设置路由断言,代理servicerId为data-service1的/ data-service1 /路径
        - id: business  # 请求 http://localhost:8100/data-service2/test转发到 http://localhost:8080/test
          uri: http://localhost:9001
          predicates:
            - Path=/business/**
          filters:
            - StripPrefix=1  #前缀， 在当前路径匹配中表示去掉第一个前缀 /business/xx -> /xxx
        - id: file  # 请求 http://localhost:8100/data-service2/test转发到 http://localhost:8080/test
          uri: http://localhost:9002
          predicates:
            - Path=/file/**
          filters:
            - StripPrefix=1  #前缀， 在当前路径匹配中表示去掉第一个前缀 /business/xx -> /xxx
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


